version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=104.154.212.61,localhost,127.0.0.1
    restart: unless-stopped
