version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8000"  # 로컬에서는 8001 포트 사용
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,192.168.41.140
    restart: unless-stopped
